// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/v1/booking.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     int64                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	PropertyId    int64                  `protobuf:"varint,2,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	GuestId       int64                  `protobuf:"varint,3,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // YYYY-MM-DD
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                        // e.g., PENDING, CONFIRMED, CANCELLED
	PaymentInfo   string                 `protobuf:"bytes,7,opt,name=payment_info,json=paymentInfo,proto3" json:"payment_info,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_api_proto_v1_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Booking) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *Booking) GetPropertyId() int64 {
	if x != nil {
		return x.PropertyId
	}
	return 0
}

func (x *Booking) GetGuestId() int64 {
	if x != nil {
		return x.GuestId
	}
	return 0
}

func (x *Booking) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Booking) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Booking) GetPaymentInfo() string {
	if x != nil {
		return x.PaymentInfo
	}
	return ""
}

func (x *Booking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Booking) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     int64                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_api_proto_v1_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_booking_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookingRequest) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

type ListGuestBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuestId       int64                  `protobuf:"varint,1,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGuestBookingsRequest) Reset() {
	*x = ListGuestBookingsRequest{}
	mi := &file_api_proto_v1_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGuestBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuestBookingsRequest) ProtoMessage() {}

func (x *ListGuestBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuestBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListGuestBookingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_booking_proto_rawDescGZIP(), []int{2}
}

func (x *ListGuestBookingsRequest) GetGuestId() int64 {
	if x != nil {
		return x.GuestId
	}
	return 0
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    int64                  `protobuf:"varint,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	GuestId       int64                  `protobuf:"varint,2,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	PaymentInfo   string                 `protobuf:"bytes,5,opt,name=payment_info,json=paymentInfo,proto3" json:"payment_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_api_proto_v1_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_booking_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBookingRequest) GetPropertyId() int64 {
	if x != nil {
		return x.PropertyId
	}
	return 0
}

func (x *CreateBookingRequest) GetGuestId() int64 {
	if x != nil {
		return x.GuestId
	}
	return 0
}

func (x *CreateBookingRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateBookingRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreateBookingRequest) GetPaymentInfo() string {
	if x != nil {
		return x.PaymentInfo
	}
	return ""
}

type BookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingResponse) Reset() {
	*x = BookingResponse{}
	mi := &file_api_proto_v1_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResponse) ProtoMessage() {}

func (x *BookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResponse.ProtoReflect.Descriptor instead.
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_booking_proto_rawDescGZIP(), []int{4}
}

func (x *BookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type ListBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsResponse) Reset() {
	*x = ListBookingsResponse{}
	mi := &file_api_proto_v1_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsResponse) ProtoMessage() {}

func (x *ListBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsResponse.ProtoReflect.Descriptor instead.
func (*ListBookingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_booking_proto_rawDescGZIP(), []int{5}
}

func (x *ListBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

var File_api_proto_v1_booking_proto protoreflect.FileDescriptor

const file_api_proto_v1_booking_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/v1/booking.proto\x12\n" +
	"booking.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x02\n" +
	"\aBooking\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x03R\tbookingId\x12\x1f\n" +
	"\vproperty_id\x18\x02 \x01(\x03R\n" +
	"propertyId\x12\x19\n" +
	"\bguest_id\x18\x03 \x01(\x03R\aguestId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12!\n" +
	"\fpayment_info\x18\a \x01(\tR\vpaymentInfo\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"2\n" +
	"\x11GetBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x03R\tbookingId\"5\n" +
	"\x18ListGuestBookingsRequest\x12\x19\n" +
	"\bguest_id\x18\x01 \x01(\x03R\aguestId\"\xaf\x01\n" +
	"\x14CreateBookingRequest\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\x03R\n" +
	"propertyId\x12\x19\n" +
	"\bguest_id\x18\x02 \x01(\x03R\aguestId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12!\n" +
	"\fpayment_info\x18\x05 \x01(\tR\vpaymentInfo\"@\n" +
	"\x0fBookingResponse\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.booking.v1.BookingR\abooking\"G\n" +
	"\x14ListBookingsResponse\x12/\n" +
	"\bbookings\x18\x01 \x03(\v2\x13.booking.v1.BookingR\bbookings2\x87\x02\n" +
	"\x0eBookingService\x12H\n" +
	"\n" +
	"GetBooking\x12\x1d.booking.v1.GetBookingRequest\x1a\x1b.booking.v1.BookingResponse\x12[\n" +
	"\x11ListGuestBookings\x12$.booking.v1.ListGuestBookingsRequest\x1a .booking.v1.ListBookingsResponse\x12N\n" +
	"\rCreateBooking\x12 .booking.v1.CreateBookingRequest\x1a\x1b.booking.v1.BookingResponseB*Z(github.com/user/airbnb-test/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_booking_proto_rawDescOnce sync.Once
	file_api_proto_v1_booking_proto_rawDescData []byte
)

func file_api_proto_v1_booking_proto_rawDescGZIP() []byte {
	file_api_proto_v1_booking_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_booking_proto_rawDesc), len(file_api_proto_v1_booking_proto_rawDesc)))
	})
	return file_api_proto_v1_booking_proto_rawDescData
}

var file_api_proto_v1_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_v1_booking_proto_goTypes = []any{
	(*Booking)(nil),                  // 0: booking.v1.Booking
	(*GetBookingRequest)(nil),        // 1: booking.v1.GetBookingRequest
	(*ListGuestBookingsRequest)(nil), // 2: booking.v1.ListGuestBookingsRequest
	(*CreateBookingRequest)(nil),     // 3: booking.v1.CreateBookingRequest
	(*BookingResponse)(nil),          // 4: booking.v1.BookingResponse
	(*ListBookingsResponse)(nil),     // 5: booking.v1.ListBookingsResponse
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
}
var file_api_proto_v1_booking_proto_depIdxs = []int32{
	6, // 0: booking.v1.Booking.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: booking.v1.Booking.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: booking.v1.BookingResponse.booking:type_name -> booking.v1.Booking
	0, // 3: booking.v1.ListBookingsResponse.bookings:type_name -> booking.v1.Booking
	1, // 4: booking.v1.BookingService.GetBooking:input_type -> booking.v1.GetBookingRequest
	2, // 5: booking.v1.BookingService.ListGuestBookings:input_type -> booking.v1.ListGuestBookingsRequest
	3, // 6: booking.v1.BookingService.CreateBooking:input_type -> booking.v1.CreateBookingRequest
	4, // 7: booking.v1.BookingService.GetBooking:output_type -> booking.v1.BookingResponse
	5, // 8: booking.v1.BookingService.ListGuestBookings:output_type -> booking.v1.ListBookingsResponse
	4, // 9: booking.v1.BookingService.CreateBooking:output_type -> booking.v1.BookingResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_v1_booking_proto_init() }
func file_api_proto_v1_booking_proto_init() {
	if File_api_proto_v1_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_booking_proto_rawDesc), len(file_api_proto_v1_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_booking_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_booking_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_booking_proto_msgTypes,
	}.Build()
	File_api_proto_v1_booking_proto = out.File
	file_api_proto_v1_booking_proto_goTypes = nil
	file_api_proto_v1_booking_proto_depIdxs = nil
}
