// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/v1/guest.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Guest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuestId       int64                  `protobuf:"varint,1,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	BookingIds    []int64                `protobuf:"varint,6,rep,packed,name=booking_ids,json=bookingIds,proto3" json:"booking_ids,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guest) Reset() {
	*x = Guest{}
	mi := &file_api_proto_v1_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guest) ProtoMessage() {}

func (x *Guest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guest.ProtoReflect.Descriptor instead.
func (*Guest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_guest_proto_rawDescGZIP(), []int{0}
}

func (x *Guest) GetGuestId() int64 {
	if x != nil {
		return x.GuestId
	}
	return 0
}

func (x *Guest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Guest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Guest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Guest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Guest) GetBookingIds() []int64 {
	if x != nil {
		return x.BookingIds
	}
	return nil
}

func (x *Guest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetGuestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuestId       int64                  `protobuf:"varint,1,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuestRequest) Reset() {
	*x = GetGuestRequest{}
	mi := &file_api_proto_v1_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuestRequest) ProtoMessage() {}

func (x *GetGuestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuestRequest.ProtoReflect.Descriptor instead.
func (*GetGuestRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_guest_proto_rawDescGZIP(), []int{1}
}

func (x *GetGuestRequest) GetGuestId() int64 {
	if x != nil {
		return x.GuestId
	}
	return 0
}

type CreateGuestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGuestRequest) Reset() {
	*x = CreateGuestRequest{}
	mi := &file_api_proto_v1_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGuestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGuestRequest) ProtoMessage() {}

func (x *CreateGuestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGuestRequest.ProtoReflect.Descriptor instead.
func (*CreateGuestRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_guest_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGuestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGuestRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateGuestRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateGuestRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type GuestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guest         *Guest                 `protobuf:"bytes,1,opt,name=guest,proto3" json:"guest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestResponse) Reset() {
	*x = GuestResponse{}
	mi := &file_api_proto_v1_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestResponse) ProtoMessage() {}

func (x *GuestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestResponse.ProtoReflect.Descriptor instead.
func (*GuestResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_guest_proto_rawDescGZIP(), []int{3}
}

func (x *GuestResponse) GetGuest() *Guest {
	if x != nil {
		return x.Guest
	}
	return nil
}

var File_api_proto_v1_guest_proto protoreflect.FileDescriptor

const file_api_proto_v1_guest_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/v1/guest.proto\x12\bguest.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n" +
	"\x05Guest\x12\x19\n" +
	"\bguest_id\x18\x01 \x01(\x03R\aguestId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1f\n" +
	"\vbooking_ids\x18\x06 \x03(\x03R\n" +
	"bookingIds\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\",\n" +
	"\x0fGetGuestRequest\x12\x19\n" +
	"\bguest_id\x18\x01 \x01(\x03R\aguestId\"n\n" +
	"\x12CreateGuestRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\"6\n" +
	"\rGuestResponse\x12%\n" +
	"\x05guest\x18\x01 \x01(\v2\x0f.guest.v1.GuestR\x05guest2\x94\x01\n" +
	"\fGuestService\x12>\n" +
	"\bGetGuest\x12\x19.guest.v1.GetGuestRequest\x1a\x17.guest.v1.GuestResponse\x12D\n" +
	"\vCreateGuest\x12\x1c.guest.v1.CreateGuestRequest\x1a\x17.guest.v1.GuestResponseB*Z(github.com/user/airbnb-test/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_guest_proto_rawDescOnce sync.Once
	file_api_proto_v1_guest_proto_rawDescData []byte
)

func file_api_proto_v1_guest_proto_rawDescGZIP() []byte {
	file_api_proto_v1_guest_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_guest_proto_rawDesc), len(file_api_proto_v1_guest_proto_rawDesc)))
	})
	return file_api_proto_v1_guest_proto_rawDescData
}

var file_api_proto_v1_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_v1_guest_proto_goTypes = []any{
	(*Guest)(nil),                 // 0: guest.v1.Guest
	(*GetGuestRequest)(nil),       // 1: guest.v1.GetGuestRequest
	(*CreateGuestRequest)(nil),    // 2: guest.v1.CreateGuestRequest
	(*GuestResponse)(nil),         // 3: guest.v1.GuestResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_api_proto_v1_guest_proto_depIdxs = []int32{
	4, // 0: guest.v1.Guest.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: guest.v1.GuestResponse.guest:type_name -> guest.v1.Guest
	1, // 2: guest.v1.GuestService.GetGuest:input_type -> guest.v1.GetGuestRequest
	2, // 3: guest.v1.GuestService.CreateGuest:input_type -> guest.v1.CreateGuestRequest
	3, // 4: guest.v1.GuestService.GetGuest:output_type -> guest.v1.GuestResponse
	3, // 5: guest.v1.GuestService.CreateGuest:output_type -> guest.v1.GuestResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_v1_guest_proto_init() }
func file_api_proto_v1_guest_proto_init() {
	if File_api_proto_v1_guest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_guest_proto_rawDesc), len(file_api_proto_v1_guest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_guest_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_guest_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_guest_proto_msgTypes,
	}.Build()
	File_api_proto_v1_guest_proto = out.File
	file_api_proto_v1_guest_proto_goTypes = nil
	file_api_proto_v1_guest_proto_depIdxs = nil
}
