// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/v1/host.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	IsVerified    bool                   `protobuf:"varint,6,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_api_proto_v1_host_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_host_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_host_proto_rawDescGZIP(), []int{0}
}

func (x *Host) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Host) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Host) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Host) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Host) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Host) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *Host) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Host) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostRequest) Reset() {
	*x = GetHostRequest{}
	mi := &file_api_proto_v1_host_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostRequest) ProtoMessage() {}

func (x *GetHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_host_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostRequest.ProtoReflect.Descriptor instead.
func (*GetHostRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_host_proto_rawDescGZIP(), []int{1}
}

func (x *GetHostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHostRequest) Reset() {
	*x = CreateHostRequest{}
	mi := &file_api_proto_v1_host_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostRequest) ProtoMessage() {}

func (x *CreateHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_host_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostRequest.ProtoReflect.Descriptor instead.
func (*CreateHostRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_host_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHostRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateHostRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateHostRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateHostRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type HostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *Host                  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostResponse) Reset() {
	*x = HostResponse{}
	mi := &file_api_proto_v1_host_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostResponse) ProtoMessage() {}

func (x *HostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_host_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostResponse.ProtoReflect.Descriptor instead.
func (*HostResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_host_proto_rawDescGZIP(), []int{3}
}

func (x *HostResponse) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

var File_api_proto_v1_host_proto protoreflect.FileDescriptor

const file_api_proto_v1_host_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/v1/host.proto\x12\ahost.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x02\n" +
	"\x04Host\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x1f\n" +
	"\vis_verified\x18\x06 \x01(\bR\n" +
	"isVerified\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\" \n" +
	"\x0eGetHostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"x\n" +
	"\x11CreateHostRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\"1\n" +
	"\fHostResponse\x12!\n" +
	"\x04host\x18\x01 \x01(\v2\r.host.v1.HostR\x04host2\x89\x01\n" +
	"\vHostService\x129\n" +
	"\aGetHost\x12\x17.host.v1.GetHostRequest\x1a\x15.host.v1.HostResponse\x12?\n" +
	"\n" +
	"CreateHost\x12\x1a.host.v1.CreateHostRequest\x1a\x15.host.v1.HostResponseB*Z(github.com/user/airbnb-test/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_host_proto_rawDescOnce sync.Once
	file_api_proto_v1_host_proto_rawDescData []byte
)

func file_api_proto_v1_host_proto_rawDescGZIP() []byte {
	file_api_proto_v1_host_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_host_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_host_proto_rawDesc), len(file_api_proto_v1_host_proto_rawDesc)))
	})
	return file_api_proto_v1_host_proto_rawDescData
}

var file_api_proto_v1_host_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_v1_host_proto_goTypes = []any{
	(*Host)(nil),                  // 0: host.v1.Host
	(*GetHostRequest)(nil),        // 1: host.v1.GetHostRequest
	(*CreateHostRequest)(nil),     // 2: host.v1.CreateHostRequest
	(*HostResponse)(nil),          // 3: host.v1.HostResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_api_proto_v1_host_proto_depIdxs = []int32{
	4, // 0: host.v1.Host.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: host.v1.Host.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: host.v1.HostResponse.host:type_name -> host.v1.Host
	1, // 3: host.v1.HostService.GetHost:input_type -> host.v1.GetHostRequest
	2, // 4: host.v1.HostService.CreateHost:input_type -> host.v1.CreateHostRequest
	3, // 5: host.v1.HostService.GetHost:output_type -> host.v1.HostResponse
	3, // 6: host.v1.HostService.CreateHost:output_type -> host.v1.HostResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_v1_host_proto_init() }
func file_api_proto_v1_host_proto_init() {
	if File_api_proto_v1_host_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_host_proto_rawDesc), len(file_api_proto_v1_host_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_host_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_host_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_host_proto_msgTypes,
	}.Build()
	File_api_proto_v1_host_proto = out.File
	file_api_proto_v1_host_proto_goTypes = nil
	file_api_proto_v1_host_proto_depIdxs = nil
}
