// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/v1/property.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Property struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HostId        int64                  `protobuf:"varint,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_api_proto_v1_property_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_property_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_property_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Property) GetHostId() int64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *Property) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Property) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Property) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Property) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Property) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetPropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    int64                  `protobuf:"varint,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertyRequest) Reset() {
	*x = GetPropertyRequest{}
	mi := &file_api_proto_v1_property_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertyRequest) ProtoMessage() {}

func (x *GetPropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_property_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertyRequest.ProtoReflect.Descriptor instead.
func (*GetPropertyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_property_proto_rawDescGZIP(), []int{1}
}

func (x *GetPropertyRequest) GetPropertyId() int64 {
	if x != nil {
		return x.PropertyId
	}
	return 0
}

type ListPropertiesByHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        int64                  `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertiesByHostRequest) Reset() {
	*x = ListPropertiesByHostRequest{}
	mi := &file_api_proto_v1_property_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertiesByHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertiesByHostRequest) ProtoMessage() {}

func (x *ListPropertiesByHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_property_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertiesByHostRequest.ProtoReflect.Descriptor instead.
func (*ListPropertiesByHostRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_property_proto_rawDescGZIP(), []int{2}
}

func (x *ListPropertiesByHostRequest) GetHostId() int64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *ListPropertiesByHostRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ListPropertiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertiesRequest) Reset() {
	*x = ListPropertiesRequest{}
	mi := &file_api_proto_v1_property_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertiesRequest) ProtoMessage() {}

func (x *ListPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_property_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertiesRequest.ProtoReflect.Descriptor instead.
func (*ListPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_property_proto_rawDescGZIP(), []int{3}
}

type CreatePropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        int64                  `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePropertyRequest) Reset() {
	*x = CreatePropertyRequest{}
	mi := &file_api_proto_v1_property_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePropertyRequest) ProtoMessage() {}

func (x *CreatePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_property_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePropertyRequest.ProtoReflect.Descriptor instead.
func (*CreatePropertyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_property_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePropertyRequest) GetHostId() int64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *CreatePropertyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePropertyRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreatePropertyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePropertyRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type PropertyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Property      *Property              `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyResponse) Reset() {
	*x = PropertyResponse{}
	mi := &file_api_proto_v1_property_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyResponse) ProtoMessage() {}

func (x *PropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_property_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyResponse.ProtoReflect.Descriptor instead.
func (*PropertyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_property_proto_rawDescGZIP(), []int{5}
}

func (x *PropertyResponse) GetProperty() *Property {
	if x != nil {
		return x.Property
	}
	return nil
}

type ListPropertiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    []*Property            `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertiesResponse) Reset() {
	*x = ListPropertiesResponse{}
	mi := &file_api_proto_v1_property_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertiesResponse) ProtoMessage() {}

func (x *ListPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_property_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertiesResponse.ProtoReflect.Descriptor instead.
func (*ListPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_property_proto_rawDescGZIP(), []int{6}
}

func (x *ListPropertiesResponse) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

var File_api_proto_v1_property_proto protoreflect.FileDescriptor

const file_api_proto_v1_property_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/v1/property.proto\x12\vproperty.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\bProperty\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\x03R\x06hostId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"5\n" +
	"\x12GetPropertyRequest\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\x03R\n" +
	"propertyId\"R\n" +
	"\x1bListPropertiesByHostRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\x03R\x06hostId\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"\x17\n" +
	"\x15ListPropertiesRequest\"\x98\x01\n" +
	"\x15CreatePropertyRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\x03R\x06hostId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\"E\n" +
	"\x10PropertyResponse\x121\n" +
	"\bproperty\x18\x01 \x01(\v2\x15.property.v1.PropertyR\bproperty\"O\n" +
	"\x16ListPropertiesResponse\x125\n" +
	"\n" +
	"properties\x18\x01 \x03(\v2\x15.property.v1.PropertyR\n" +
	"properties2\xf7\x02\n" +
	"\x0fPropertyService\x12M\n" +
	"\vGetProperty\x12\x1f.property.v1.GetPropertyRequest\x1a\x1d.property.v1.PropertyResponse\x12e\n" +
	"\x14ListPropertiesByHost\x12(.property.v1.ListPropertiesByHostRequest\x1a#.property.v1.ListPropertiesResponse\x12S\n" +
	"\x0eCreateProperty\x12\".property.v1.CreatePropertyRequest\x1a\x1d.property.v1.PropertyResponse\x12Y\n" +
	"\x0eListProperties\x12\".property.v1.ListPropertiesRequest\x1a#.property.v1.ListPropertiesResponseB*Z(github.com/user/airbnb-test/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_property_proto_rawDescOnce sync.Once
	file_api_proto_v1_property_proto_rawDescData []byte
)

func file_api_proto_v1_property_proto_rawDescGZIP() []byte {
	file_api_proto_v1_property_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_property_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_property_proto_rawDesc), len(file_api_proto_v1_property_proto_rawDesc)))
	})
	return file_api_proto_v1_property_proto_rawDescData
}

var file_api_proto_v1_property_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_v1_property_proto_goTypes = []any{
	(*Property)(nil),                    // 0: property.v1.Property
	(*GetPropertyRequest)(nil),          // 1: property.v1.GetPropertyRequest
	(*ListPropertiesByHostRequest)(nil), // 2: property.v1.ListPropertiesByHostRequest
	(*ListPropertiesRequest)(nil),       // 3: property.v1.ListPropertiesRequest
	(*CreatePropertyRequest)(nil),       // 4: property.v1.CreatePropertyRequest
	(*PropertyResponse)(nil),            // 5: property.v1.PropertyResponse
	(*ListPropertiesResponse)(nil),      // 6: property.v1.ListPropertiesResponse
	(*timestamppb.Timestamp)(nil),       // 7: google.protobuf.Timestamp
}
var file_api_proto_v1_property_proto_depIdxs = []int32{
	7, // 0: property.v1.Property.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: property.v1.PropertyResponse.property:type_name -> property.v1.Property
	0, // 2: property.v1.ListPropertiesResponse.properties:type_name -> property.v1.Property
	1, // 3: property.v1.PropertyService.GetProperty:input_type -> property.v1.GetPropertyRequest
	2, // 4: property.v1.PropertyService.ListPropertiesByHost:input_type -> property.v1.ListPropertiesByHostRequest
	4, // 5: property.v1.PropertyService.CreateProperty:input_type -> property.v1.CreatePropertyRequest
	3, // 6: property.v1.PropertyService.ListProperties:input_type -> property.v1.ListPropertiesRequest
	5, // 7: property.v1.PropertyService.GetProperty:output_type -> property.v1.PropertyResponse
	6, // 8: property.v1.PropertyService.ListPropertiesByHost:output_type -> property.v1.ListPropertiesResponse
	5, // 9: property.v1.PropertyService.CreateProperty:output_type -> property.v1.PropertyResponse
	6, // 10: property.v1.PropertyService.ListProperties:output_type -> property.v1.ListPropertiesResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_v1_property_proto_init() }
func file_api_proto_v1_property_proto_init() {
	if File_api_proto_v1_property_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_property_proto_rawDesc), len(file_api_proto_v1_property_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_property_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_property_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_property_proto_msgTypes,
	}.Build()
	File_api_proto_v1_property_proto = out.File
	file_api_proto_v1_property_proto_goTypes = nil
	file_api_proto_v1_property_proto_depIdxs = nil
}
