// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/v1/wishlist.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WishlistItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GuestId       int64                  `protobuf:"varint,2,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
	PropertyId    int64                  `protobuf:"varint,3,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WishlistItem) Reset() {
	*x = WishlistItem{}
	mi := &file_api_proto_v1_wishlist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WishlistItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishlistItem) ProtoMessage() {}

func (x *WishlistItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_wishlist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishlistItem.ProtoReflect.Descriptor instead.
func (*WishlistItem) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_wishlist_proto_rawDescGZIP(), []int{0}
}

func (x *WishlistItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WishlistItem) GetGuestId() int64 {
	if x != nil {
		return x.GuestId
	}
	return 0
}

func (x *WishlistItem) GetPropertyId() int64 {
	if x != nil {
		return x.PropertyId
	}
	return 0
}

func (x *WishlistItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AddToWishlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuestId       int64                  `protobuf:"varint,1,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
	PropertyId    int64                  `protobuf:"varint,2,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToWishlistRequest) Reset() {
	*x = AddToWishlistRequest{}
	mi := &file_api_proto_v1_wishlist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToWishlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToWishlistRequest) ProtoMessage() {}

func (x *AddToWishlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_wishlist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToWishlistRequest.ProtoReflect.Descriptor instead.
func (*AddToWishlistRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_wishlist_proto_rawDescGZIP(), []int{1}
}

func (x *AddToWishlistRequest) GetGuestId() int64 {
	if x != nil {
		return x.GuestId
	}
	return 0
}

func (x *AddToWishlistRequest) GetPropertyId() int64 {
	if x != nil {
		return x.PropertyId
	}
	return 0
}

type WishlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *WishlistItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WishlistResponse) Reset() {
	*x = WishlistResponse{}
	mi := &file_api_proto_v1_wishlist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WishlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishlistResponse) ProtoMessage() {}

func (x *WishlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_wishlist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishlistResponse.ProtoReflect.Descriptor instead.
func (*WishlistResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_wishlist_proto_rawDescGZIP(), []int{2}
}

func (x *WishlistResponse) GetItem() *WishlistItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetWishlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuestId       int64                  `protobuf:"varint,1,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWishlistRequest) Reset() {
	*x = GetWishlistRequest{}
	mi := &file_api_proto_v1_wishlist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWishlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWishlistRequest) ProtoMessage() {}

func (x *GetWishlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_wishlist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWishlistRequest.ProtoReflect.Descriptor instead.
func (*GetWishlistRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_wishlist_proto_rawDescGZIP(), []int{3}
}

func (x *GetWishlistRequest) GetGuestId() int64 {
	if x != nil {
		return x.GuestId
	}
	return 0
}

type GetWishlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WishlistItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWishlistResponse) Reset() {
	*x = GetWishlistResponse{}
	mi := &file_api_proto_v1_wishlist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWishlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWishlistResponse) ProtoMessage() {}

func (x *GetWishlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_wishlist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWishlistResponse.ProtoReflect.Descriptor instead.
func (*GetWishlistResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_wishlist_proto_rawDescGZIP(), []int{4}
}

func (x *GetWishlistResponse) GetItems() []*WishlistItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_proto_v1_wishlist_proto protoreflect.FileDescriptor

const file_api_proto_v1_wishlist_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/v1/wishlist.proto\x12\vwishlist.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n" +
	"\fWishlistItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bguest_id\x18\x02 \x01(\x03R\aguestId\x12\x1f\n" +
	"\vproperty_id\x18\x03 \x01(\x03R\n" +
	"propertyId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"R\n" +
	"\x14AddToWishlistRequest\x12\x19\n" +
	"\bguest_id\x18\x01 \x01(\x03R\aguestId\x12\x1f\n" +
	"\vproperty_id\x18\x02 \x01(\x03R\n" +
	"propertyId\"A\n" +
	"\x10WishlistResponse\x12-\n" +
	"\x04item\x18\x01 \x01(\v2\x19.wishlist.v1.WishlistItemR\x04item\"/\n" +
	"\x12GetWishlistRequest\x12\x19\n" +
	"\bguest_id\x18\x01 \x01(\x03R\aguestId\"F\n" +
	"\x13GetWishlistResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.wishlist.v1.WishlistItemR\x05items2\xb6\x01\n" +
	"\x0fWishlistService\x12Q\n" +
	"\rAddToWishlist\x12!.wishlist.v1.AddToWishlistRequest\x1a\x1d.wishlist.v1.WishlistResponse\x12P\n" +
	"\vGetWishlist\x12\x1f.wishlist.v1.GetWishlistRequest\x1a .wishlist.v1.GetWishlistResponseB*Z(github.com/user/airbnb-test/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_wishlist_proto_rawDescOnce sync.Once
	file_api_proto_v1_wishlist_proto_rawDescData []byte
)

func file_api_proto_v1_wishlist_proto_rawDescGZIP() []byte {
	file_api_proto_v1_wishlist_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_wishlist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_wishlist_proto_rawDesc), len(file_api_proto_v1_wishlist_proto_rawDesc)))
	})
	return file_api_proto_v1_wishlist_proto_rawDescData
}

var file_api_proto_v1_wishlist_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_v1_wishlist_proto_goTypes = []any{
	(*WishlistItem)(nil),          // 0: wishlist.v1.WishlistItem
	(*AddToWishlistRequest)(nil),  // 1: wishlist.v1.AddToWishlistRequest
	(*WishlistResponse)(nil),      // 2: wishlist.v1.WishlistResponse
	(*GetWishlistRequest)(nil),    // 3: wishlist.v1.GetWishlistRequest
	(*GetWishlistResponse)(nil),   // 4: wishlist.v1.GetWishlistResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_api_proto_v1_wishlist_proto_depIdxs = []int32{
	5, // 0: wishlist.v1.WishlistItem.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: wishlist.v1.WishlistResponse.item:type_name -> wishlist.v1.WishlistItem
	0, // 2: wishlist.v1.GetWishlistResponse.items:type_name -> wishlist.v1.WishlistItem
	1, // 3: wishlist.v1.WishlistService.AddToWishlist:input_type -> wishlist.v1.AddToWishlistRequest
	3, // 4: wishlist.v1.WishlistService.GetWishlist:input_type -> wishlist.v1.GetWishlistRequest
	2, // 5: wishlist.v1.WishlistService.AddToWishlist:output_type -> wishlist.v1.WishlistResponse
	4, // 6: wishlist.v1.WishlistService.GetWishlist:output_type -> wishlist.v1.GetWishlistResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_v1_wishlist_proto_init() }
func file_api_proto_v1_wishlist_proto_init() {
	if File_api_proto_v1_wishlist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_wishlist_proto_rawDesc), len(file_api_proto_v1_wishlist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_wishlist_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_wishlist_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_wishlist_proto_msgTypes,
	}.Build()
	File_api_proto_v1_wishlist_proto = out.File
	file_api_proto_v1_wishlist_proto_goTypes = nil
	file_api_proto_v1_wishlist_proto_depIdxs = nil
}
