package host

import (
	"time"
)

// Model represents the GORM schema for a Host
type Model struct {
	ID         int64     `gorm:"primaryKey;autoIncrement"`
	UserName   string    `gorm:"column:user_name;type:varchar(100)"`
	Email      string    `gorm:"column:email;type:varchar(100);unique"`
	Phone      string    `gorm:"column:phone;type:varchar(100)"`
	Location   string    `gorm:"column:location;type:varchar(255)"`
	IsVerified bool      `gorm:"column:is_verified"`
	CreatedAt  time.Time `gorm:"column:created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at"`
}

// TableName overrides the default table name generated by GORM
func (Model) TableName() string {
	return "hosts"
}
