package property

import (
	"time"
)

// Model represents the GORM schema for a Property
type Model struct {
	ID          int64     `gorm:"primaryKey;autoIncrement"`
	HostID      int64     `gorm:"column:host_id;index"`
	Name        string    `gorm:"column:name;type:varchar(255)"`
	Location    string    `gorm:"column:location;type:varchar(255)"`
	Description string    `gorm:"column:description;type:varchar(500)"`
	Price       int64     `gorm:"column:price"`
	CreatedAt   time.Time `gorm:"column:created_at"`
}

// TableName overrides the default table name generated by GORM
func (Model) TableName() string {
	return "properties"
}
