// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://havenstay.localhost/terms",
        "contact": {
            "name": "HavenStay Platform Support",
            "url": "https://github.com/AshutoshKY/havenstay-backend",
            "email": "api-support@havenstay.local"
        },
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/bookings": {
            "get": {
                "description": "Poll the history of all active, past, and cancelled reservations tied to a specific Guest profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookings"
                ],
                "summary": "Get a Guest's Booking History",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "The ID of the Guest requesting their itinerary.",
                        "name": "guestId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "An array of all historical and upcoming bookings for the Guest.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.ListBookingsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Missing or invalid guest ID.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "Securely initiates a booking transaction for a specific Property by a Guest.\nThe system will evaluate the requested dates, calculate total pricing, and attempt to reserve the asset.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookings"
                ],
                "summary": "Create a Booking Reservation",
                "parameters": [
                    {
                        "description": "Payload specifying the Guest ID, Property ID, Start Date, End Date, and calculated total price.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.CreateBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Reservation successfully created and locked.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.BookingResponse"
                        }
                    },
                    "400": {
                        "description": "Validation Bad Request - Overlapping dates or missing required fields.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/bookings/{id}": {
            "get": {
                "description": "Fetch an exact copy of a completed or pending Booking reservation by its unique confirmation ID.\nTypical use-case: Displaying a digital receipt or itinerary details to the Guest.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookings"
                ],
                "summary": "Retrieve Booking Invoice",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "The numeric Reservation/Booking ID.",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The retrieved itinerary and invoice details.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.BookingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid ID format.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found - The reservation does not exist.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/guests": {
            "post": {
                "description": "Creates a new Guest profile. Guests are users who can book properties and create wishlists.\nEnsure the email address provided is unique across the platform.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Guests"
                ],
                "summary": "Register a new Guest",
                "parameters": [
                    {
                        "description": "Payload containing the Guest's personal details (Name, Email, Phone).",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.CreateGuestRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Guest successfully registered and assigned a unique ID.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.GuestResponse"
                        }
                    },
                    "400": {
                        "description": "Validation Error - Invalid payload format or duplicate email.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/guests/{id}": {
            "get": {
                "description": "Fetches the profile and identity data for a specific Guest by their unique numeric identifier.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Guests"
                ],
                "summary": "Retrieve Guest details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "The unique numeric ID of the Guest to retrieve.",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The requested Guest details.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.GuestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - The provided ID was invalid.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found - No Guest exists with the provided ID.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/hosts": {
            "post": {
                "description": "Creates a new Host profile on the platform. Hosts are independent users capable of listing and managing multiple Properties.\nNote: A newly created host is automatically marked as ` + "`" + `is_verified: false` + "`" + ` pending administrator approval.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hosts"
                ],
                "summary": "Register a new Host",
                "parameters": [
                    {
                        "description": "Payload containing the Host's basic contact and profile information (Name, Email, Phone, Location).",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.CreateHostRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Host successfully registered and assigned a unique ID.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.HostResponse"
                        }
                    },
                    "400": {
                        "description": "Validation Error - Invalid email format or missing required fields.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Database connection failure.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/hosts/{id}": {
            "get": {
                "description": "Fetches the complete public profile of a Host by their unique identifier natively from the core system.\nUse this endpoint to display a Host's verification status, contact info, and join date on their public landing page.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hosts"
                ],
                "summary": "Retrieve Host details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "The unique numeric ID of the Host to retrieve.",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The requested Host details were found and returned successfully.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.HostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - The provided ID was not a valid integer.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found - No Host exists with the provided ID.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/lists": {
            "get": {
                "description": "Fetches the complete array of bookmarked properties saved under a specific Guest account.\nActs as the primary data source for the \"Saved Homes\" UI tab.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wishlists"
                ],
                "summary": "View Guest Wishlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "The target Guest's unique Identifier.",
                        "name": "guestId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "An array wrapping the nested Property details saved by the user.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.GetWishlistResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "Bookmarks a specific property to a Guest's curated wishlist for later viewing or booking.\nUseful for encouraging users to return to properties they found engaging.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wishlists"
                ],
                "summary": "Save Property to Wishlist",
                "parameters": [
                    {
                        "description": "Payload connecting a Guest ID to a Property ID.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.AddToWishlistRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "A confirmation object encapsulating the newly bookmarked item constraint.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.WishlistResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Duplicate bookmark or invalid identifiers.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/properties": {
            "get": {
                "description": "Retrieve a sweeping list of all active property listings on the HavenStay platform.\n*(Note: In future versions, this will include global pagination and bounding-box map filters).*",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "Browse all Properties",
                "responses": {
                    "200": {
                        "description": "A comprehensive array of all available properties.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.ListPropertiesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error while querying the database.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "An authenticated Host can use this endpoint to publish a new real-estate listing.\nNote: You MUST pass a valid ` + "`" + `host_id` + "`" + ` representing an already-registered Host on the platform, or the database foreign-key constraint will reject the listing.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "List a new Property",
                "parameters": [
                    {
                        "description": "The core details of the listing: Name, Description, Location String, and Nightly Price (Float).",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.CreatePropertyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Property was published and is now live on the index.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.PropertyResponse"
                        }
                    },
                    "400": {
                        "description": "Validation Bad Request - Usually missing Host ID or malformed price.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/properties/host/{hostId}": {
            "get": {
                "description": "Get all properties listed specifically by one Host.\nThis endpoint powers the \"Host Dashboard\", allowing property owners to see all assets they have under management. Optionally, you can pass a ` + "`" + `location` + "`" + ` query to filter the host's properties by a specific city.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "Host's Dashboard Properties",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "The Host ID managing these properties.",
                        "name": "hostId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Optional string to filter the resulting list by a specific city or region.",
                        "name": "location",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "A list of properties bound to the specified host.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.ListPropertiesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/properties/{id}": {
            "get": {
                "description": "Drill down into a specific property. Returns the exact title, host bindings, textual description, nightly price, and location coordinates formatted for front-end rendering.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "Get Property Details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "The exact Property ID to inspect.",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Full property overview returned.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.PropertyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Property Not Found - the listing may have been deactivated.",
                        "schema": {
                            "$ref": "#/definitions/github_com_user_airbnb-test_internal_pkg_response.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_user_airbnb-test_api_proto_v1.AddToWishlistRequest": {
            "type": "object",
            "properties": {
                "guest_id": {
                    "type": "integer"
                },
                "property_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.Booking": {
            "type": "object",
            "properties": {
                "booking_id": {
                    "type": "integer"
                },
                "created_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "end_date": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "guest_id": {
                    "type": "integer"
                },
                "payment_info": {
                    "type": "string"
                },
                "property_id": {
                    "type": "integer"
                },
                "start_date": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "status": {
                    "description": "e.g., PENDING, CONFIRMED, CANCELLED",
                    "type": "string"
                },
                "updated_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.BookingResponse": {
            "type": "object",
            "properties": {
                "booking": {
                    "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.Booking"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.CreateBookingRequest": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "guest_id": {
                    "type": "integer"
                },
                "payment_info": {
                    "type": "string"
                },
                "property_id": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.CreateGuestRequest": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.CreateHostRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.CreatePropertyRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "host_id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.GetWishlistResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.WishlistItem"
                    }
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.Guest": {
            "type": "object",
            "properties": {
                "booking_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "country": {
                    "type": "string"
                },
                "created_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "email": {
                    "type": "string"
                },
                "guest_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.GuestResponse": {
            "type": "object",
            "properties": {
                "guest": {
                    "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.Guest"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.Host": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_verified": {
                    "type": "boolean"
                },
                "location": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "updated_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.HostResponse": {
            "type": "object",
            "properties": {
                "host": {
                    "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.Host"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.ListBookingsResponse": {
            "type": "object",
            "properties": {
                "bookings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.Booking"
                    }
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.ListPropertiesResponse": {
            "type": "object",
            "properties": {
                "properties": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.Property"
                    }
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.Property": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "description": {
                    "type": "string"
                },
                "host_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.PropertyResponse": {
            "type": "object",
            "properties": {
                "property": {
                    "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.Property"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.WishlistItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "guest_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "property_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_user_airbnb-test_api_proto_v1.WishlistResponse": {
            "type": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/github_com_user_airbnb-test_api_proto_v1.WishlistItem"
                }
            }
        },
        "github_com_user_airbnb-test_internal_pkg_response.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "details": {
                    "type": "string",
                    "example": "missing required field 'guestId'"
                },
                "message": {
                    "type": "string",
                    "example": "status bad request"
                }
            }
        },
        "timestamppb.Timestamp": {
            "type": "object",
            "properties": {
                "nanos": {
                    "description": "Non-negative fractions of a second at nanosecond resolution. This field is\nthe nanosecond portion of the duration, not an alternative to seconds.\nNegative second values with fractions must still have non-negative nanos\nvalues that count forward in time. Must be between 0 and 999,999,999\ninclusive.",
                    "type": "integer"
                },
                "seconds": {
                    "description": "Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must\nbe between -315576000000 and 315576000000 inclusive (which corresponds to\n0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z).",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "HavenStay - Hotel & Room Booking API",
	Description:      "Welcome to the HavenStay Backend API documentation! 🚀\n\nHavenStay is a modern, high-performance Domain-Driven Design (DDD) backend built in Go. It empowers Hosts to manage luxury properties and Guests to seamlessly book remote getaways.\n\n### Key Features:\n- **🏘️ Property Management**: Full CRUD lifecycle for short-term rentals and luxury homes.\n- **👩\u200d💼 Host & Guest Profiles**: Independent onboarding and profile management domains.\n- **📅 Booking Engine**: Real-time reservation creation.\n- **❤️ Wishlists**: Guests can curate lists of favorite properties.\n\n**Built With**: Go 1.21+, Gin (REST), gRPC, Protobufs, MySQL 8, GORM.\n\n📥 **[Download Postman Collection](https://raw.githubusercontent.com/AshutoshKY/havenstay-backend/master/postman_collection.json)**",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
